spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
#    hibernate:
#      ddl-auto: create
server:
  port: 8009